-- Run AFTER supabase-smart-sheet-v53b.sql and supabase-access-entitlements-v1.sql.
-- Additive migration. No users, exports, or existing entitlement values are deleted.
begin;
do $$ begin
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='profiles' and column_name='exports_unlimited') then
    raise exception 'Run supabase-access-entitlements-v1.sql first';
  end if;
  if not exists (select 1 from auth.users where lower(email)='masterprintlabcorp@gmail.com' and email_confirmed_at is not null) then
    raise exception 'Existing verified owner masterprintlabcorp@gmail.com must exist before this migration';
  end if;
end $$;

alter table public.profiles drop constraint if exists profiles_role_check;
alter table public.profiles add constraint profiles_role_check check (role in ('user','customer','admin'));
alter table public.profiles alter column role set default 'user';
alter table public.profiles add column if not exists full_name text not null default '';
alter table public.profiles add column if not exists business_name text not null default '';
alter table public.profiles add column if not exists mobile text not null default '';
alter table public.profiles add column if not exists city text not null default '';
alter table public.profiles add column if not exists country text not null default '';
alter table public.profiles add column if not exists machine_type text not null default '';
alter table public.profiles add column if not exists monthly_usage text not null default '';
alter table public.profiles add column if not exists terms_accepted_at timestamptz;
-- NULL inherits legacy plan/exports_unlimited. Explicit Standard can override a legacy subscription.
alter table public.profiles add column if not exists export_access_override text check (export_access_override in ('standard','unlimited'));
alter table public.profiles add column if not exists is_super_admin boolean not null default false;
create unique index if not exists profiles_one_super_admin on public.profiles (is_super_admin) where is_super_admin;

-- Bind the EXISTING verified owner UUID once. Email changes never move this grant.
insert into public.profiles(id,email,role,plan)
select id,lower(email),'user','free' from auth.users where email is not null
on conflict (id) do nothing;
update public.profiles set is_super_admin=true
where id=(select id from auth.users where lower(email)='masterprintlabcorp@gmail.com' and email_confirmed_at is not null)
and not exists (select 1 from public.profiles where is_super_admin);

create table if not exists public.user_access_history (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id),
  actor_id uuid references auth.users(id),
  event text not null,
  old_value jsonb,
  new_value jsonb,
  created_at timestamptz not null default now()
);
create index if not exists user_access_history_user_date on public.user_access_history(user_id,created_at desc,id desc);
create index if not exists usage_exports_user_date on public.usage_exports(user_id,counted_at desc,id desc);
alter table public.user_access_history enable row level security;
revoke all on public.user_access_history from public,anon,authenticated;
revoke all on public.usage_exports from public,anon,authenticated;
grant all on public.user_access_history to service_role;
grant usage,select on sequence public.user_access_history_id_seq to service_role;
revoke insert,update,delete on public.profiles from public,anon,authenticated;
-- A restrictive read policy also protects against any older broad permissive policy.
drop policy if exists profiles_self_read_guard on public.profiles;
create policy profiles_self_read_guard on public.profiles as restrictive for select to authenticated using (id=auth.uid());

create or replace function public.ssb_register_profile() returns trigger
language plpgsql security definer set search_path=public,pg_temp as $$
declare m jsonb := coalesce(new.raw_user_meta_data,'{}'::jsonb);
begin
  if new.email is null then return new; end if;
  insert into public.profiles(id,email,role,plan,status,exports_used,exports_unlimited,
    full_name,business_name,mobile,city,country,machine_type,monthly_usage,terms_accepted_at)
  values(new.id,lower(new.email),'user','free','active',0,false,
    left(coalesce(m->>'full_name',''),120),left(coalesce(m->>'business_name',''),160),
    left(coalesce(m->>'mobile',''),40),left(coalesce(m->>'city',''),100),left(coalesce(m->>'country',''),100),
    case when m->>'machine_type' in ('DTF','UV-DTF','Tarpaulin','Other') then m->>'machine_type' else '' end,
    left(coalesce(m->>'monthly_usage',''),100),case when m->>'terms_accepted'='true' then now() end)
  on conflict(id) do nothing;
  insert into public.user_access_history(user_id,actor_id,event,new_value)
  values(new.id,new.id,'registration',jsonb_build_object('role','user','export_access','standard',
    'account_status',case when new.email_confirmed_at is null then 'pending_email_verification' else 'active' end));
  return new;
end $$;
drop trigger if exists ssb_register_profile on auth.users;
create trigger ssb_register_profile after insert on auth.users for each row execute function public.ssb_register_profile();

create or replace function public.ssb_require_owner(p_actor uuid) returns void
language plpgsql security definer set search_path=public,pg_temp as $$
begin
  if not exists(select 1 from public.profiles p join auth.users u on u.id=p.id
    where p.id=p_actor and p.is_super_admin and p.status='active' and u.email_confirmed_at is not null) then
    raise exception 'Super Admin required' using errcode='42501';
  end if;
end $$;

create or replace function public.ssb_unlimited(p public.profiles) returns boolean
language sql stable set search_path=public,pg_temp as $$
  select p.is_super_admin or case when p.export_access_override is not null
    then p.export_access_override='unlimited' else p.exports_unlimited or p.plan in ('subscriber','admin') or p.role='admin' end
$$;

create or replace function public.ssb_admin_users(p_actor uuid,p_search text default '',p_status text default '',p_access text default '',p_offset integer default 0)
returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare result jsonb;
begin
  perform public.ssb_require_owner(p_actor);
  with users as (
    select p.id,p.full_name,u.email,u.created_at,u.email_confirmed_at,p.is_super_admin,
      case when p.status='blocked' then 'suspended' when u.email_confirmed_at is null then 'pending_email_verification' else 'active' end as account_status,
      case when public.ssb_unlimited(p) then 'unlimited' else 'standard' end as export_access
    from public.profiles p join auth.users u on u.id=p.id
  ), filtered as (
    select * from users where (p_search='' or position(lower(left(p_search,200)) in lower(full_name||' '||coalesce(email,'')))>0)
      and (p_status='' or account_status=p_status) and (p_access='' or export_access=p_access)
  ) select jsonb_build_object('total',(select count(*) from filtered),'users',coalesce((
    select jsonb_agg(to_jsonb(page) order by page.created_at desc,page.id) from
    (select * from filtered order by created_at desc,id limit 30 offset greatest(0,least(p_offset,1000000))) page),'[]'::jsonb)) into result;
  return result;
end $$;

create or replace function public.ssb_admin_user(p_actor uuid,p_target uuid,p_offset integer default 0)
returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare result jsonb;
begin
  perform public.ssb_require_owner(p_actor);
  select to_jsonb(p)||jsonb_build_object('email',u.email,'registered_at',u.created_at,'last_sign_in_at',u.last_sign_in_at,
    'email_confirmed_at',u.email_confirmed_at,'account_status',case when p.status='blocked' then 'suspended' when u.email_confirmed_at is null then 'pending_email_verification' else 'active' end,
    'export_access',case when public.ssb_unlimited(p) then 'unlimited' else 'standard' end,
    'remaining',case when public.ssb_unlimited(p) then null else greatest(0,5-p.exports_used) end,
    'can_manage_design_library',p.is_super_admin and p.status='active' and u.email_confirmed_at is not null,
    'recorded_exports',(select count(*) from public.usage_exports where user_id=p.id)) into result
  from public.profiles p join auth.users u on u.id=p.id where p.id=p_target;
  if result is null then raise exception 'User not found' using errcode='P0002'; end if;
  return jsonb_build_object('user',result,'history',coalesce((select jsonb_agg(to_jsonb(h) order by h.created_at desc,h.sort_key desc) from (
    select * from (
      select 'audit-'||a.id as sort_key,a.event,a.old_value,a.new_value,a.created_at,a.actor_id,au.email as actor_email
      from public.user_access_history a left join auth.users au on au.id=a.actor_id where a.user_id=p_target
      union all
      select 'export-'||e.id,'export',null,jsonb_build_object('format',e.export_kind),e.counted_at,e.user_id,null
      from public.usage_exports e where e.user_id=p_target
    ) events order by created_at desc,sort_key desc limit 30 offset greatest(0,least(p_offset,1000000))
  ) h),'[]'::jsonb));
end $$;

create or replace function public.ssb_admin_change(p_actor uuid,p_target uuid,p_field text,p_value text,p_expected timestamptz)
returns void language plpgsql security definer set search_path=public,pg_temp as $$
declare p public.profiles; old_data jsonb; new_data jsonb;
begin
  perform public.ssb_require_owner(p_actor);
  select * into p from public.profiles where id=p_target for update;
  if not found then raise exception 'User not found' using errcode='P0002'; end if;
  if p.is_super_admin or p.id=p_actor then raise exception 'Owner critical access is protected' using errcode='42501'; end if;
  if p_expected is null or p.updated_at<>p_expected then raise exception 'Account changed. Refresh and review again.' using errcode='40001'; end if;
  if p_field='export_access' and p_value in ('standard','unlimited') then
    old_data=jsonb_build_object('export_access',case when public.ssb_unlimited(p) then 'unlimited' else 'standard' end);
    new_data=jsonb_build_object('export_access',p_value);
    if old_data=new_data then return; end if;
    update public.profiles set export_access_override=p_value,exports_unlimited=(p_value='unlimited'),updated_at=clock_timestamp() where id=p_target;
  elsif p_field='status' and p_value in ('active','blocked') then
    old_data=jsonb_build_object('status',p.status); new_data=jsonb_build_object('status',p_value);
    if old_data=new_data then return; end if;
    update public.profiles set status=p_value,updated_at=clock_timestamp() where id=p_target;
  else raise exception 'Only export access and account status may be changed' using errcode='22023'; end if;
  insert into public.user_access_history(user_id,actor_id,event,old_value,new_value)
  values(p_target,p_actor,'admin_access_change',old_data,new_data);
end $$;

-- Serialize a suspension/access change with a consume request; never grant from a stale profile.
create or replace function public.ssb_consume_export(p_user uuid,p_kind text)
returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare p public.profiles;
begin
  select * into p from public.profiles where id=p_user for update;
  if not found then raise exception 'Profile missing'; end if;
  if p.status='blocked' then return jsonb_build_object('allowed',false,'reason','account_blocked','message','This account is suspended. Contact support.','profile',to_jsonb(p)); end if;
  if not exists(select 1 from auth.users where id=p_user and email_confirmed_at is not null) then
    return jsonb_build_object('allowed',false,'reason','email_unverified','message','Verify your email before exporting.','profile',to_jsonb(p));
  end if;
  if not public.ssb_unlimited(p) then
    if p.exports_used>=5 then return jsonb_build_object('allowed',false,'reason','limit_reached','message','Your free account has used all 5 trial exports.','profile',to_jsonb(p)); end if;
    update public.profiles set exports_used=exports_used+1 where id=p_user returning * into p;
  end if;
  insert into public.usage_exports(user_id,export_kind) values(p_user,left(coalesce(p_kind,'download'),40));
  return jsonb_build_object('allowed',true,'profile',to_jsonb(p));
end $$;

create or replace function public.ssb_import_guest_usage(p_user uuid,p_guest text)
returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare p public.profiles; n integer;
begin
  select * into p from public.profiles where id=p_user for update;
  if not found then raise exception 'Profile missing'; end if;
  if p.status='blocked' then raise exception 'Account suspended' using errcode='42501'; end if;
  if not exists(select 1 from auth.users where id=p_user and email_confirmed_at is not null) then raise exception 'Verify your email' using errcode='42501'; end if;
  select least(5,exports_used) into n from public.guest_usage where guest_id=p_guest;
  if not public.ssb_unlimited(p) and coalesce(n,0)>p.exports_used then
    update public.profiles set exports_used=n where id=p_user returning * into p;
  end if;
  return to_jsonb(p);
end $$;

-- Only Next server endpoints holding the service key may call these functions.
revoke all on function public.ssb_register_profile(),public.ssb_require_owner(uuid),public.ssb_unlimited(public.profiles),
  public.ssb_admin_users(uuid,text,text,text,integer),public.ssb_admin_user(uuid,uuid,integer),
  public.ssb_admin_change(uuid,uuid,text,text,timestamptz),public.ssb_consume_export(uuid,text),public.ssb_import_guest_usage(uuid,text)
from public,anon,authenticated;
grant execute on function public.ssb_require_owner(uuid),public.ssb_admin_users(uuid,text,text,text,integer),
  public.ssb_admin_user(uuid,uuid,integer),public.ssb_admin_change(uuid,uuid,text,text,timestamptz),
  public.ssb_consume_export(uuid,text),public.ssb_import_guest_usage(uuid,text) to service_role;
notify pgrst,'reload schema';
commit;
