const assert = require('node:assert/strict');
const { fixture } = require('./client-jobs.test.cjs');
const { NextRequest } = require('next/server');
(async () => {
  const f = await fixture();
  const originalEnv = { ...process.env };
  const get = async (token) => {
    const r = await f.pub.GET(f.req('/api/client-upload/' + token), { params: { token } });
    return { status: r.status, ...await r.json() };
  };
  try {
    const initial = await (await f.owner.GET(f.req('/', undefined, 'basic'))).json();
    assert.equal(initial.portal.active, false);
    const token = initial.portal.url.split('/').at(-1);
    assert.match(token, /^[A-Za-z0-9_-]{43}$/);
    assert.equal((await get(token)).code, 'portal_disabled');
    delete process.env.RESEND_API_KEY;
    const setup = await (await f.owner.GET(f.req('/', undefined, 'basic'))).json();
    assert(setup.setupIssues.some(x => x.includes('RESEND_API_KEY')));
    assert.equal((await get(token)).message, 'This upload portal is currently disabled.');
    assert.equal((await f.owner.POST(f.req('/', { action: 'save', settings: initial.portal.settings }, 'basic'))).status, 503);
    assert.equal((await f.one('select enabled from client_portals where owner_id=$1', [f.users.basic.id])).enabled, false);
    process.env.RESEND_API_KEY = originalEnv.RESEND_API_KEY;
    const enabled = await f.portal();
    assert.equal(enabled, token, 'enable persists and retains generated token');
    assert.deepEqual(await get(token), { status: 200, shopName: 'Test shop' });
    const active = await (await f.owner.GET(f.req('/', undefined, 'basic'))).json();
    assert.equal(active.portal.active, true);
    assert.equal(active.portal.url, 'https://shop.test/client-upload/' + token);
    assert.equal((await get('x'.repeat(43))).code, 'portal_not_found');
    assert.equal((await get('invalid')).code, 'portal_not_found');
    const draft = await f.call('create', token);
    await f.q("update client_jobs set expires_at=clock_timestamp()-interval '1 second' where id=$1", [draft.job.id]);
    assert.equal((await f.call('preview', token, draft.submission)).code, 'submission_expired');
    const rotated = await (await f.owner.POST(f.req('/', { action: 'rotate' }, 'basic'))).json();
    const replacement = rotated.portal.url.split('/').at(-1);
    assert.notEqual(replacement, token);
    assert.equal((await get(token)).code, 'portal_not_found');
    assert.equal((await get(replacement)).status, 200);
    delete process.env.RESEND_API_KEY;
    assert.equal((await get(replacement)).code, 'portal_configuration_error');
    process.env.RESEND_API_KEY = originalEnv.RESEND_API_KEY;
    await f.owner.POST(f.req('/', { action: 'disable' }, 'basic'));
    assert.equal((await get(replacement)).code, 'portal_disabled');
    assert.equal((await f.portal()), replacement, 're-enable retains replacement');
    const serviceKey = process.env.SUPABASE_SERVICE_ROLE_KEY;
    delete process.env.SUPABASE_SERVICE_ROLE_KEY;
    assert.equal((await get(replacement)).code, 'portal_configuration_error');
    process.env.SUPABASE_SERVICE_ROLE_KEY = serviceKey;
    // A deployment running the earlier SQL must ask for its schema update, not a new customer link.
    const oldError = Object.assign(Error('Upload link unavailable. Ask the shop for a new link.'), { data: { code: 'P0002' } });
    assert.equal((await f.lib.errorReply(oldError).json()).code, 'portal_setup_required');
    const deniedRpc = Object.assign(Error('permission denied for function ssb_client_jobs'), { data: { code: '42501' } });
    assert.equal(f.lib.errorReply(deniedRpc).status, 503, 'broken server grants are configuration failures, not invalid links');
    await f.q('alter function ssb_client_jobs(text,uuid,text,uuid,jsonb) rename to temporarily_missing_client_jobs');
    const missing = await get(replacement);
    assert.equal(missing.status, 503);
    assert.equal(missing.code, 'portal_setup_required');
    assert(!missing.message.includes('Ask the shop for a new link'));
    await f.q('alter function temporarily_missing_client_jobs(text,uuid,text,uuid,jsonb) rename to ssb_client_jobs');
    process.env.NODE_ENV = 'production';
    delete process.env.VERCEL;
    process.env.SMART_SHEET_SITE_URL = 'https://smart-sheet-builder.vercel.app';
    assert.equal(f.lib.publicOrigin(new NextRequest('http://localhost:3000/api/client-jobs')), 'http://localhost:3000');
    process.env.VERCEL = '1';
    assert.equal(f.lib.publicOrigin(new NextRequest('https://smart-sheet-builder.vercel.app/api/client-jobs')), 'https://smart-sheet-builder.vercel.app');
    process.env.SMART_SHEET_SITE_URL = 'http://localhost:3000';
    assert.throws(() => f.lib.publicOrigin(f.req('/')));
    process.env.SMART_SHEET_SITE_URL = 'https://user:password@example.test';
    assert.throws(() => f.lib.publicOrigin(f.req('/')));
    delete process.env.SMART_SHEET_SITE_URL;
    process.env.VERCEL_ENV = 'production';
    process.env.VERCEL_PROJECT_PRODUCTION_URL = 'smart-sheet-builder.vercel.app';
    assert.equal(f.lib.publicOrigin(new NextRequest('https://attacker.test/')), 'https://smart-sheet-builder.vercel.app');
    console.log('PASS: saved opaque links, enable/disable/rotate/re-enable, anonymous resolution, expired sessions, missing configuration/schema diagnostics, owner setup status, localhost/production origins and Host-injection rejection.');
  } finally {
    for (const key of Object.keys(process.env)) if (!(key in originalEnv)) delete process.env[key];
    Object.assign(process.env, originalEnv);
    await f.close();
  }
})().catch(e => { console.error(e); process.exitCode = 1; });
